services:
  web:
    container_name: dolibarr_web
    image: dolibarr/dolibarr:latest
    environment:
      WWW_USER_ID: ${WWW_USER_ID}
      WWW_GROUP_ID: ${WWW_GROUP_ID}
      PHP_INI_UPLOAD_MAX_FILESIZE: ${PHP_INI_UPLOAD_MAX_FILESIZE}
      PHP_INI_DATE_TIMEZONE: ${PHP_INI_DATE_TIMEZONE}

      DOLI_DB_HOST: ${DOLI_DB_HOST}
      DOLI_DB_NAME: ${DOLI_DB_NAME}
      DOLI_DB_USER: ${DOLI_DB_USER}
      DOLI_DB_PASSWORD: ${DOLI_DB_PASSWORD}
      DOLI_URL_ROOT: ${DOLI_URL_ROOT}

      DOLI_ADMIN_LOGIN: ${DOLI_ADMIN_LOGIN}
      DOLI_ADMIN_PASSWORD: ${DOLI_ADMIN_PASSWORD}

      DOLI_COMPANY_NAME: ${DOLI_COMPANY_NAME}
      DOLI_COMPANY_COUNTRYCODE: ${DOLI_COMPANY_COUNTRYCODE}
    ports:
      - ${DOLI_HOST_PORT}:${DOLI_DOCKER_PORT}
    links:
      - db
    volumes:
      - ./custom:/var/www/html/custom
      - ./documents:/var/www/documents
    restart: always

  db:
    container_name: dolibarr_db
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DOLI_DB_NAME}
      MARIADB_USER: ${DOLI_DB_USER}
      MARIADB_PASSWORD: ${DOLI_DB_PASSWORD}
      TZ: ${PHP_INI_DATE_TIMEZONE}
    ports:
      - ${MARIADB_HOST_PORT}:${MARIADB_DOCKER_PORT}
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: always

  phpmyadmin:
    container_name: dolibarr_phpmyadmin
    image: phpmyadmin:latest
    ports:
      - ${PMA_HOST_PORT}:${PMA_DOCKER_PORT}
    links:
      - db
    depends_on:
      - db
    restart: always

  adminer:
    container_name: dolibarr_adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: ${DOLI_DB_HOST}
    volumes:
      - ./adminer/adminer.css:/var/www/html/adminer.css
    ports:
      - ${ADM_HOST_PORT}:${ADM_DOCKER_PORT}
    depends_on:
      - db
    restart: always
